### ISSUE TITLE
As a user I'd like an easy way to browse through the many instances of a model, so that I can easily navigate the site.

### ISSUE THREAD

**Issue by nico1utaustin** [kattawar/canitstreamtome#47]
Estimated Time: A few days

Assumptions:  There is a hopefully a React pagination component integrateable with Bootstrap

**Comment by erinjensby** [comment]
I have found the google React pagination component.  Integrating this will allow users to browse many instances of a model at a time.

**Comment by erinjensby** [comment]
Updated estimated time: 1 day

**Comment by nico1utaustin** [comment]
I integrated pagination it took 3 days
