### ISSUE TITLE
As a power user, I'd eventually like to search for specific movies, so that I can find specific movies I want.

### ISSUE THREAD

**Issue by nico1utaustin** [kattawar/canitstreamtome#49]
Estimated time: 1 week

**Comment by kevinsalcedo** [comment]
This will be a little more complicated, but it's pretty doable. What would probably be required is to give the user filtering options as well as a search bar. The info that the user enters here will be appended to the request to our API

**Comment by kevinsalcedo** [comment]
Actual time: 1 week. Done!
