### ISSUE TITLE
As  a user I want to see what movies are popular in what country, so that I can be up to date on current trends.

### ISSUE THREAD

**Issue by nico1utaustin** [kattawar/canitstreamtome#51]
estimated time: A few days

We will need twitter api and google trends for this

**Comment by erinjensby** [comment]
Zach has figured out how to use the twitter api and google trends to gather this information.  Once it is in the database I will be able to add it to the front-end of our website.

**Comment by erinjensby** [comment]
Updated estimated time: 2 days

**Comment by kevinsalcedo** [comment]
Actal time: 3 days
