### ISSUE TITLE
As a user I want to be able to get a lot of information about a movie (i.e. trailer, cast), so that I can decide if I want to watch it

### ISSUE THREAD

**Issue by nico1utaustin** [kattawar/canitstreamtome#53]
Estimated time: a few weeks

This is dependent on api and react so it is more involved

**Comment by erinjensby** [comment]
I have found themoviedb's api has all of this information available. We will be using this information and  React to display this information.
Updated estimated time: a few days

**Comment by kevinsalcedo** [comment]
Actual time: 3 days
