### ISSUE TITLE
As a user I want to be able to get to the page I want to get to quickly, so that I can find things quickly.

### ISSUE THREAD

**Issue by nico1utaustin** [kattawar/canitstreamtome#54]
Estimated time: a few days

This involves implementing the nav bar.

**Comment by erinjensby** [comment]
I found a navbar tutorial and will be able to add it to our website.
Updated estimated time: 1 day

**Comment by erinjensby** [comment]
I have added the NavBar users will now be able to navigate our pages quickly.

**Comment by kevinsalcedo** [comment]
TIme: < 1 day
