### ISSUE TITLE
As a user, I'd like to know the name and release year of a movie before clicking on it and going to its individual page.

### ISSUE THREAD

**Issue by erinjensby** [kattawar/canitstreamtome#55]
Estimated time: 2 days

**Comment by nico1utaustin** [comment]
We can implement some sort of component that shows movie title along with other info when you hover over the instance.

**Comment by nico1utaustin** [comment]
https://stackoverflow.com/questions/32125708/how-can-i-access-a-hover-state-in-reactjs

**Comment by kevinsalcedo** [comment]
Actual time: 1 day
