### ISSUE TITLE
As a user, I'd like to know the name of a streaming service or country before clicking on it.

### ISSUE THREAD

**Issue by erinjensby** [kattawar/canitstreamtome#56]
Estimated time: 1 day

**Comment by nico1utaustin** [comment]
For this one we can just add these attributes to the instance components we don't need to do hover like the movies page since that was more for aesthetics

**Comment by kevinsalcedo** [comment]
Maybe we should still add the instance names underneath each poster, just for some clarity

**Comment by QuantumSoundings** [comment]
Finished!

**Comment by kevinsalcedo** [comment]
Actual time: 3 days
