### ISSUE TITLE
Write the API documentation

### ISSUE THREAD

**Issue by erinjensby** [kattawar/canitstreamtome#63]
https://www.gitbook.com/book/kevinsalcedo/api/welcome

**Comment by erinjensby** [comment]
Instructor notes: -2 No information about what parameters the endpoints take; -1 No error responses (invalid IDs, etc); -1 No way to enumerate all valid IDs/names. This inconveniences the users of the API and will increase your server load as users try to do so manually by endless loop; -1 Unorganized. All of it is on one page. If this API were to be expanded, it would be inconvenient for the user to find endpoints for different models;

**Comment by QuantumSoundings** [comment]
Finished!
