### ISSUE TITLE
As a user, I'd like to search for countries containing certain keywords (i.e. a specific region) so that I can easily find countries in regions i am interested in.

### ISSUE THREAD

**Issue by erinjensby** [kattawar/canitstreamtome#76]

**Comment by nico1utaustin** [comment]
We can maybe get all data and search on user side rather than server using javascript for the search

**Comment by kevinsalcedo** [comment]
We ended up going server-side for this. Searching by region and filtering by region are both done
Estiamted time: 2 days
Actual time: 2 days
