### ISSUE TITLE
As a user, I would like more information on the Streaming Services model pages

### ISSUE THREAD

**Issue by zaralouis** [kattawar/canitstreamtome#90]
The Streaming Services model pages are quite sparse compared to the other model pages
Compare the screenshot of the "Hulu" model page (Streaming Services) to the "13 Hours" page (Movie)

<img width="1261" alt="screen shot 2018-04-11 at 12 48 15 pm" src="https://user-images.githubusercontent.com/14898278/38633940-bcf21484-3d86-11e8-9e49-61fa77805e3c.png">
<img width="1258" alt="screen shot 2018-04-11 at 12 47 55 pm" src="https://user-images.githubusercontent.com/14898278/38633934-b8ba01f6-3d86-11e8-9351-2eb232ab43b6.png">

**Comment by erinjensby** [comment]
We're not sure what other information could be provided for each streaming service.  If you have an idea of something that can be added to every streaming service let us know.
