### ISSUE TITLE
As a user, I think that the ability to filter countries by their main language would be helpful.

### ISSUE THREAD

**Issue by ramdeepk2** [kattawar/canitstreamtome#92]
It would be useful to a person who is only interested in English films (or perhaps foreign-language films). It may help them establish how English films become popular in non-English speaking countries as well.

**Comment by erinjensby** [comment]
We have already implemented filtering by certain languages. Will can add more to make it more robust.

**Comment by erinjensby** [comment]
Actually I am not sure what you're asking. Please clarify as the title does not seem to correlate to the description.

**Comment by ramdeepk2** [comment]
Sorry, I was talking about movies. I thought it would be nice if there were some foreign language films (not too many, maybe just the most popular ones) so a person could learn about them through the site.

**Comment by kevinsalcedo** [comment]
Unfortunately we don't have the data to implement this functionality
