### ISSUE TITLE
As a user, I'd appreciate it if the appearance of a search term in the title of the movie gave it some priority over films in which a search term is only in the description.

### ISSUE THREAD

**Issue by ramdeepk2** [kattawar/canitstreamtome#93]
Here is an example: the search term is 'what', but "What We Do in the Shadows" is behind "Room" on page 3:
![capture](https://user-images.githubusercontent.com/25390627/38636363-947e5628-3d8d-11e8-9192-7aa39ddedcf7.PNG)

**Comment by erinjensby** [comment]
We are working on a solution to this problem. We would like our API to return models with the search term in the title first, then those with the search term in the description, then all other fields.

Estimated time: 2 days
