### ISSUE TITLE
As a user, I would like to see more information on the cards for each model

### ISSUE THREAD

**Issue by roshan-dongre** [kattawar/canitstreamtome#94]
<img width="1195" alt="screen shot 2018-04-11 at 5 17 10 pm" src="https://user-images.githubusercontent.com/14967965/38646098-4068f650-3dac-11e8-8015-a2656ec0498a.png">

The models are a little cramped and maybe more information on each card and more even spacing would be nice.

**Comment by nico1utaustin** [comment]
In an effort to reduce clutter we have all relevant information if a user hovers over the instance. We also originally had more spacing but we're told by Downing to have that many per row.

**Comment by roshan-dongre** [comment]
Hmm yeah I was saying that because on the streaming services grid page you only have one page which makes it look kinda weird since you have a pagination bar. If Downing told you to keep it that way lmk and I can change the user story to something else
