### ISSUE TITLE
As a user, I would like to see a more user friendly about page

### ISSUE THREAD

**Issue by roshan-dongre** [kattawar/canitstreamtome#95]
<img width="1272" alt="screen shot 2018-04-11 at 5 19 14 pm" src="https://user-images.githubusercontent.com/14967965/38646172-7dad827e-3dac-11e8-98a0-189152ed796f.png">

Right now there seems to be a lot of information on the about page but not a consistent/clean way to show the information

**Comment by erinjensby** [comment]
I made the about page cleaner and more condensed.  It should now be more user friendly.

**Comment by erinjensby** [comment]
Estimated time was: 1 hour
Actual time was: 15 min
