### ISSUE TITLE
As a user, I want a more clear description of the popularity rankings.

### ISSUE THREAD

**Issue by rp27537** [kattawar/canitstreamtome#96]
It is confusing to see that the most popular movie in the USA is an anime from 1987. By reading the technical report, I can learn that popularity is determined by the number of Google searches done for that movie, so you might consider changing the category titles "Top Movies" and "Popular Countries" to something that more clearly indicates this.

![top_movies](https://user-images.githubusercontent.com/25215391/38646744-d2ae952c-3dae-11e8-8b81-387b36799c3f.png)

![popular_countries](https://user-images.githubusercontent.com/25215391/38646752-d7b6de94-3dae-11e8-9d9b-e9113055dc89.png)

**Comment by kevinsalcedo** [comment]
That's a really good point - I've changed the titles from 'Top Movies' and 'Popular Countries' to 'Top Trending Movies' and 'Top Trending In', respectively. I hope this is a more accurate statement of what the information reflects. Let us know if that's better!

**Comment by rp27537** [comment]
Those titles sound like they describe the information much more accurately. Thank you!

**Comment by erinjensby** [comment]
Estimated time was: 10 min
Actual time: 10 min
