### ISSUE TITLE
As a user, I want the search results to be easier to navigate.

### ISSUE THREAD

**Issue by rp27537** [kattawar/canitstreamtome#97]
Currently, the search results show only three items per page, and looking through multiple pages is difficult because the result boxes keep changing height and moving the page numbers with them. Increasing the number of results per page and keeping the navigation in place will improve the user experience.

**Comment by nico1utaustin** [comment]
We can definitely show another row and will fix the height issue by having static height

**Comment by erinjensby** [comment]
Estimate Time: 1 day
