### ISSUE TITLE
As a user, I would like to have an uncluttered search page

### ISSUE THREAD

**Issue by larius11** [kattawar/canitstreamtome#99]
When making a search and results are not found for a specific model the message saying that nothing was found takes up a large amount of the screen. If instead you only display the models that have results that would make the search much cleaner.  Only return the "nothing found" message when nothing is found on any models.

**Comment by kevinsalcedo** [comment]
I've done what you've suggested, I do agree it looks much cleaner!

**Comment by erinjensby** [comment]
Estimated time was: 2 hrs
Actual time: 20 min
